name: itvlist

on:
  schedule:
    - cron: '0 10,20 * * *' # 每天6:00和18:00运行
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: pip install selenium==4.19.0 requests==2.31.0 futures==3.0.5 eventlet==0.36.1

      - name: Run cctv
        run: python ${{ github.workspace }}/new.py
        
      - name: 提交更改
        run: |
          git config --local user.email "luiquirong@gmail.com"
          git config --local user.name "yd072"
          git add *.txt *.m3u
          git commit -m "Add generated files"
          git push -f
